name: CICD

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configurer node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Installation des dépendances
        run: npm install

      - name: Lancement des tests unitaires
        run: npm run test

      - name: Build de l'application
        run: npm run build

      - name: Test du dist (liste du dossier dist)
        run: ls -la ./dist
      
      - name: Upload du dossier dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3  

      - name: Déploiement sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
